### ISSUE TITLE
Spanish translation.

### ISSUE THREAD

**Issue by vidimus** [strategywizard/Unspeakable-One-Repository#1]
Hello, @strategywizard 

As usual, would you mind if I translate your scenario into Spanish?

**Comment by strategywizard** [comment]
Of course, I would appreciate it! 
Daniel ScottCell: 318-469-1502E-mail: bdetsst@yahoo.com

 

    On Saturday, December 26, 2020, 05:52:10 AM CST, vidimus <notifications@github.com> wrote:  
 
 


Hello, @strategywizard

As usual, would you mind if I translate your scenario into Spanish?

**Comment by vidimus** [comment]
Great! I will start as soon as I finish the current translation I'm now
doing.

**Comment by vidimus** [comment]
@strategywizard , translation is finished. This weekend I will test it. If I see any bug or issue, I will report it here or on Discord.

**Comment by vidimus** [comment]
Here's the save game. Defeating Hastur doesn't trigger the end of the scenario.

[save3.zip](https://github.com/strategywizard/Unspeakable-One-Repository/files/6064781/save3.zip)
